workflows:
  ios-simulator-screenshots:
    name: iOS Simulator Build for Appetize
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS simulator app
        script: |
          flutter build ios \
            --simulator \
            --debug \
            -t lib/main.dart
    artifacts:
      - build/ios/iphonesimulator/Runner.app
